[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.20"
  SECRETS_SCAN_ENABLED = "false"

# Disable secret scanning for this project
[build.processing.secrets_scanning]
  enabled = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist" 